### ISSUE TITLE
Trace functionality doesn't work any longer

### ISSUE THREAD

**Issue by codebude** [dbeck121/ConVista-CPI-Helper-Chrome-Extension#1]
The ajax call for activating the trace mode fails with an HTTP 403 error. It worked for some days, but now it's broken. It seems like it is checking the Referer now.

Unfortunately you can't set the "Referer" header in your Ajax calls, because it is forbidden by security policy. (https://stackoverflow.com/a/33144144/251719)

Maybe you could move the functionality of calling the Trace mode url from the content script to the background script. (I think it should be possible to set request header for webrequests (https://developer.chrome.com/extensions/webRequest) in the background script.) A possible solution would be to send just an event from the contentscript to the background script and then handle the call in the background script as described here: https://developer.chrome.com/extensions/messaging

Best regards

**Comment by dbeck121** [comment]
hi @codebude ,

thanks for the post. I get the XCSRF token from the background and do the call from the front page. So your suggestion is right. Sth is missing but it was the XCSRF Token.

Normally I catch the token from a listener script that captures a specific request with the xcsrf token and sends it via message to the page script. Seems like this was not well initialised.

From chrome help:
Listeners must be registered synchronously from the start of the page.

```
  chrome.runtime.onInstalled.addListener(function() {
    chrome.contextMenus.create({
      "id": "sampleContextMenu",
      "title": "Sample Context Menu",
      "contexts": ["selection"]
    });
  });

  // This will run when a bookmark is created.
  chrome.bookmarks.onCreated.addListener(function() {
    // do something
  });
```

Do not register listeners asynchronously, as they will not be properly triggered.
//I did exactly this

 ```
 chrome.runtime.onInstalled.addListener(function() {
    // ERROR! Events must be registered synchronously from the start of
    // the page.
    chrome.bookmarks.onCreated.addListener(function() {
      // do something
    });
  });
```

so I rearranged that and I hope it is working now. When the addon is installed this should have worked before but after chrome restart, the listener was not activated anymore. Can you check if it works in 0.5.5? I will upload it directly.

**Comment by codebude** [comment]
Hi Daniel,

I tested with version 0.56 (https://github.com/dbeck121/ConVista-CPI-Helper-Chrome-Extension/blob/master/bin/ConVista-CPI-Helper-Chrome-Extension.zip) and it seems to work pretty fine. Thanks for the quick fix! (Feel free to close the issues if you have no further questions.)

**Comment by dbeck121** [comment]
Perfect. Takes some time until it is accepted by Google Chrome Store.

Thanks for your help.
