### ISSUE TITLE
Toolbar with step next/prev

### ISSUE THREAD

**Issue by bdbais** [dbeck121/ConVista-CPI-Helper-Chrome-Extension#11]
Hi,
Is it possible to have 2 buttons to move forward and back on trace steps? (another button could be a play button with timed move from steps, cool for presentation)
If is it possible to have a detached window refreshed with payload automatically loaded?
thx and compliment for this great plugin

**Comment by dbeck121** [comment]
Hi bdais,

good idea. Unfortunately I do not have much time to implement but code contributions are always welcome.
The next feature is an integration to groovyide
https://blogs.sap.com/2020/04/06/faster-groovy-development-for-sap-cpi-without-installing-an-ide/
