### ISSUE TITLE
CPI helper disappear in latest CPI environment

### ISSUE THREAD

**Issue by SAPNickYang** [dbeck121/ConVista-CPI-Helper-Chrome-Extension#12]
Hello community,

CPI helper is not showing properly (show and then disappear) in latest CPI environment (3.26.7).
Please see below screen recording.
![2020-06-13_11h08_02](https://user-images.githubusercontent.com/13759617/84556694-90280500-ad67-11ea-8d74-95cc0a903e50.gif)
I remember CPI helper links were always there before. Now I have to click "Edit" very quickly before CPI helper appear.

**Comment by codebude** [comment]
Same problem over here. I guess it's this line of code: https://github.com/dbeck121/ConVista-CPI-Helper-Chrome-Extension/blob/46e9ca00736afd7a8453679d0fd7e4168180114b/contentScript.js#L1527
From doing a quick check, it looks like, there is no element with this id any longer. Maybe you could check for the id of the editor toolbar (id="*toolBarCntrl") as criteria for a successful page load?

**Comment by dbeck121** [comment]
Thanks for reporting. I will have a look on Monday.

@codebude
Perfect. I don't think this will take long

**Comment by Chaitanya161992** [comment]
Hi Team,

CPI Helper is completely Disappeared from the Screen.
I removed it and again added the extension. Still not working.
![Capture](https://user-images.githubusercontent.com/61981691/84611228-d356b500-aeda-11ea-90f3-699b6914b002.PNG)

**Comment by dbeck121** [comment]
I uploaded a new version to google chrome store. Can you confirm that the error os solved with 1.2.1? I think it might take some houres until the version is released.

**Comment by SAPNickYang** [comment]
Thank you Dominic for fixing the issue, but still waiting for the latest version to be released to chrome web store. Not sure why it takes such long time.

**Comment by IvoVermeer** [comment]
Hi all,

I got the new version of the extension pushed today. I can see the buttons when I load an artifact, but when I go into Edit more, the buttons disappear again. It seems like SAP is re-rendering all elements or something. Is anyone having the same issue?

**Comment by SAPNickYang** [comment]
@IvoVermeer 
Yes, I encountered the same.
It seems not totally fixed. My temporary workaround is I open groovy editor and then back to flow design screen. Quite often helper links will appear.

**Comment by IvoVermeer** [comment]
Ok, I've been researching a better way of adding the buttons to the screen. I'll see if I can come up with a fix. @dbeck121 Will you be working on the issue too?

**Comment by dbeck121** [comment]
@IvoVermeer 

yes I do. I have some time today to fix this.

**Comment by IvoVermeer** [comment]
I'm trying to find out what happens exaclty, so I added a `MutationObserver`. It's observing all changes to the document and whenever the target's ID is `__xmlview0--iflowObjectPageHeader-actions`, it'll log the `MutationRecord`. I found that when you click Edit, the buttons are all removed from the screen:
![image](https://user-images.githubusercontent.com/5347891/85110759-ab858b00-b213-11ea-93bc-11e5bbbebeda.png)

@dbeck121 Maybe the `waitForElementToDisplay()` function can be replaced with a `MutationObserver`. In that observer you then simply query changes for all elements that you want to act on when added/changed/deleted etc? As long as there is just one observer running on the page, it should have no impact to performance.

**Comment by dbeck121** [comment]
Good news. I released 1.2.2. 
This time it should work well. Thank you all very much for your contribution. This saved a lot of time. 
You will get the update as soon as it is released in Chrome Store. Last time this took around 1 day. Normally it is released within houres.

The CPI really seams to render the buttons new during runtime. Also the id changes for example if a button is called __button16 and you go back to the dashboard and again in the designer, the button is now __button56

@IvoVermeer 
I used your code and to switch to mutation observer was my first choice. Everything worked well but at some points it did not catch all changes when coming back from the dasboard in CPI. I am not sure if the buttonbar is hidden and renamed at some point. 
I did now the easiest thing I can do... I check every 4 seconds if we need the buttons.
Nevertheless I will check mutation observer again. I think thats way better than my solution.

**Comment by SAPNickYang** [comment]
After a half day of use CPI plus CPI helper, I confirm the problem is fixed.
Great job!

**Comment by IvoVermeer** [comment]
> Good news. I released 1.2.2.
> This time it should work well. Thank you all very much for your contribution. This saved a lot of time.
> You will get the update as soon as it is released in Chrome Store. Last time this took around 1 day. Normally it is released within houres.
> 
> The CPI really seams to render the buttons new during runtime. Also the id changes for example if a button is called __button16 and you go back to the dashboard and again in the designer, the button is now __button56
> 
> @IvoVermeer
> I used your code and to switch to mutation observer was my first choice. Everything worked well but at some points it did not catch all changes when coming back from the dasboard in CPI. I am not sure if the buttonbar is hidden and renamed at some point.
> I did now the easiest thing I can do... I check every 4 seconds if we need the buttons.
> Nevertheless I will check mutation observer again. I think thats way better than my solution.

Yeah, switching to the `MutationObserver` would have been a major overhaul I think. I will take your comment and test it a couple of time over the next few weeks to see if we can make it work. 
Let's hope that SAP doesn't make more changes to the DOM.
