### ISSUE TITLE
Feature Req: Artifact name, as custom tab name

### ISSUE THREAD

**Issue by DennisSentler** [dbeck121/ConVista-CPI-Helper-Chrome-Extension#19]
Having custom tab names, is a great idea (which is already implemented and working fine). 
As an extension to that, I'd suggest to have an option. Which sets the artifact name, or package name, as the tab title. But just as an alternative to the custom defined tab title.
![image](https://user-images.githubusercontent.com/27735947/110950334-016f0580-8344-11eb-8d6a-6127df50d0ff.png)

**Comment by dbeck121** [comment]
Hi Dennis,

good Idea, I will take it with me for one of the next releases.

Best regards
Dominic

**Comment by DennisSentler** [comment]
@dbeck121 nice to hear that. I'm using your plugin on daily basis, it's the perfect tool for me. 

Keep up the good work.
Cheers
Dennis

**Comment by dbeck121** [comment]
Hi, 

the iflow name can be set in the tab name with version 1.4.0.

Unfortunately it might take some time until google accepts this version. So you have to be patient :)

Best regards
Dominic

**Comment by DennisSentler** [comment]
Great! Thanks for implementing the requested feature.
