### ISSUE TITLE
[Feature request] Show start status in General Information

### ISSUE THREAD

**Issue by methar2v** [dbeck121/ConVista-CPI-Helper-Chrome-Extension#21]
Hi.

Please add "SemanticState" to General Information

**Comment by dbeck121** [comment]
Hi @methar2v,

it already is:

![image](https://user-images.githubusercontent.com/54773577/116796372-1eba8780-aadc-11eb-8e15-2363ad19adc5.png)

Or do you mean sth different?

**Comment by methar2v** [comment]
Oh, sorry, I mean that info is need in "messagesx panel

**Comment by dbeck121** [comment]
Hi,
I checked that but it feels like semanticState is behind deploy State.
If I deploy new, semanticState still sais Started even if you get 404 when reaching the flow. When the flow is already deployed and usable, deployState saie DEPLOYED and semanticState still sais STARTING.

What is your use case for semanticState? deployState sounds way more accurat but maybe I am wrong here.

Best regards

**Comment by methar2v** [comment]
Hi, sometimes info panel shows: DEPLOYED & STARTING especially for large flows & need to wait some time to see DEPLOYED & STARTED

**Comment by dbeck121** [comment]
Right. But in my experience the "STARTING" indicator is useless. Whenever it is deployed the flow is running or do you have other experience?

**Comment by methar2v** [comment]
No, i don't :-) it is only personal convenience

**Comment by methar2v** [comment]
Ok. Not relevant
