### ISSUE TITLE
Content Before Step clarification

### ISSUE THREAD

**Issue by dgraversen** [dbeck121/ConVista-CPI-Helper-Chrome-Extension#4]
It is probably better to call this Body or Payload than trace. 
![2020-04-07_17-47-39](https://user-images.githubusercontent.com/33207/78690715-1a7f6300-78f8-11ea-805c-aed7b92b975d.jpg)

**Comment by dbeck121** [comment]
Good point, I will fix this in the next version.

**Comment by dbeck121** [comment]
fixed in 1.1
