### ISSUE TITLE
Close symbol is not place correctly in the header of the plugin

### ISSUE THREAD

**Issue by SAPNickYang** [dbeck121/ConVista-CPI-Helper-Chrome-Extension#5]
Close symbol X is right after header ConVista CPI Helper
![image](https://user-images.githubusercontent.com/13759617/78958968-f6589780-7b2c-11ea-9bf0-ac1059391531.png)
It looks like CSS modal_close used by close symbol X is missing from contentscript.css.
Also, the name of CSS in manifest.json is content**S**cript.css not its filename content**s**cript.css. Not sure this cause any problem or not.

Regards,
Nick

**Comment by dbeck121** [comment]
oh you are right.
I moved the css to an external file the last version and one item was missing. I fixed it and renamed the css file althought this did not seem to cause problems.
Version 1.1.1 is out

**Comment by dbeck121** [comment]
Version is out, bug fixed :-)
