### ISSUE TITLE
The final payload in the trace is not visible

### ISSUE THREAD

**Issue by VishnAndr** [dbeck121/ConVista-CPI-Helper-Chrome-Extension#9]
First of all - thank you very much for such a great tool!! It really brings joy to CPI development and monitoring!

However, I have an issue. In the example below, it's not possible to see the final payload. Meaning I can't see the result of the ERP_COD_RegisteredProd.. mapping.
If I click on the message mapping artifact, I can see the payload before the mapping only.

![image](https://user-images.githubusercontent.com/4543139/80567463-92910280-8a38-11ea-8c50-2ab64fe5a8fd.png)

In standard tracing, I can see the result, if I click on the last envelope in SOAP adapter.

![image](https://user-images.githubusercontent.com/4543139/80567445-886f0400-8a38-11ea-87e7-d3fdba5b8b27.png)

**Comment by dbeck121** [comment]
Hi @VishnAndr,

It is working in my plugin but it is hard to click on the right position. It is on my list to improve that.

When InlineTrace is on, you have to hit the text next to the arrow.

![grafik](https://user-images.githubusercontent.com/54773577/80579764-dcfb8a80-8a0a-11ea-8618-d464a240843f.png)

Can you try that?

**Comment by VishnAndr** [comment]
Hi @dbeck121 ,

Thanks mate! It worked!

Would you like to keep this issue open for future improvement? If not, I'm cool to close it.
